#          ___      _   _           _  _             _
#         | _ ) ___| |_| |_ ___ _ _| || |___ __ _ __| |___
#         | _ \/ -_)  _|  _/ -_) '_| __ / -_) _` / _` (_-<
#         |___/\___|\__|\__\___|_| |_||_\___\__,_\__,_/__/
#                           by AlonsoAliaga
#          https://www.spigotmc.org/resources/authors/281176/
#              Support server: alonsoaliaga.com/discord
#        Subscribe to my Youtube channel: alonsoaliaga.com/play
#          Subscribe to my Twitch: alonsoaliaga.com/twitch
#            Donate using Paypal: alonsoaliaga.com/donate
Messages:
  Updating: "&cDatabase is updating! Please wait.."
  No-permission: "&cYou don't have permission to do this."
  No-permission-for-head: "&cYou don't have permission for this head :("
  Reloaded: "&aSome messages and options have been reloaded. Other may require a restart!"
  Invalid-player: "&cPlayer is not online!"
  Invalid-head-id: "&cInvalid head id provided!"
  Invalid-category: "&cInvalid category provided!"
  Invalid-number: "&cAmount is not valid!"
  Not-enough-levels: "&cYou don't have enough levels to purchase this head! You need {COST} level(s)."
  Not-enough-money: "&cYou don't have enough money to purchase this head. You need ${COST}."
  Not-enough-material: "&cYou don't have enough materials to purchase this head. You need {COST} {MATERIAL}."
  Purchased-levels: "&eYou purchased &b{NAME}&e head using {COST} level(s)."
  Purchased-money: "&eYou purchased &b{NAME}&e head using ${COST}."
  Purchased-material: "&eYou purchased &b{NAME}&e head using {COST} {MATERIAL}."
  Help:
    Admin:
    - "&4&l /betterheads &r&f- &cOpen heads GUI"
    - "&4&l /betterheads get <head-id> &r&f- &cGet head with specific ID"
    - "&4&l /betterheads head [player] [receiver] &r&f- &cGet head from player name"
    - "&4&l /betterheads giverandom <player> <category> <amount> &r&f- &cGive random heads from category"
    - "&4&l /betterheads open <player> &r&f- &cOpen heads GUI for player"
    - "&4&l /betterheads build <player> <texture> &r&f- &cBuild head for player with texture"
    - "&4&l /betterheads search <term> (-name) &r&f- &cSearch heads"
    - "&4&l /betterheads reload &r&f- &cReload configuration (Not heads)"
    User:
    - "&4&l /betterheads &r&f- &cOpen heads GUI"
    - "&4&l /betterheads head [player] &r&f- &cGet head from player name"
    - "&4&l /betterheads search <term> (-name) &r&f- &cSearch heads"
  Head:
    No-permission-for-your-head: "&cYou don't have permission to get your head :("
    No-permission-for-other: "&cYou don't have permission to get heads from players :("
    No-permission-to-other: "&cYou don't have permission to give heads to others :("
    Received-your-head: "&aYou received your head!"
    Received-a-head: "&aYou received a head!"
    Gave-a-head: "&aYou gave a head to {TARGET}!"
  Build:
    Head-name: "&eBetterHead"
    Success: "&aYou built a custom head for {TARGET}."
    Success-other: "&6You received a custom head!"
    Success-other-extra: "&aYou received a custom head. You didn't have enough space, some items were thrown in the floor!"
  Get:
    Success: "&eYou received &b{HEAD}&e head!"
  Cooldown:
    Please-wait: "&cYou are getting heads too fast! Please wait {TIME} to get more."
  Give-random:
    Sent-random: "&aYou sent {AMOUNT} random heads to {PLAYER}."
    Received-random: "&aYou received {AMOUNT} random heads!"
    Received-random-extra: "&aYou received {AMOUNT} random heads. Your inventory was full, check the floor!"
  Search:
    Title: "&8Search results ({PAGE}/{MAX})"
    No-permission: "&cYou don't have access to search function. Purchase &a[RANK]&c rank!"
    Word-required: "&cYou must enter at least a word."
    Invalid-length: "&cYou must provide a word with at least {LENGTH} letters."
    No-results: "&cCouldn't find any head with those words :("
    Cooldown-please-wait: "&cYou are searching heads too fast! Please wait {TIME} to search againa."

Permissions:
  Admin: "betterheads.admin"
  #Operators DON'T HAVE THIS BY DEFAULT.
  #Permission to get your player head.
  Player-head: "betterheads.player-head"
  #Permission to get a head based on player name.
  Player-head-other: "betterheads.player-head.other"
  #Permission to get/give a head based on player name to a target player.
  Player-head-to-other: "betterheads.player-head.to-other"
  #Operators DON'T HAVE THIS BY DEFAULT.
  Free: "betterheads.free"
  #Operators DON'T HAVE THIS BY DEFAULT.
  Cooldown-bypass: "betterheads.cooldownbypass"
  #Heads permission can be "none" to not require permission to use /bheads to open categories GUI.
  #"none" can be used inside categories.yml file to remove permission for categories.
  Heads: "none"
  #Permission to use search function.
  Search: "betterheads.search"
  #Permission to bypass minimum length of words to search.
  Search-bypass-length: "betterheads.search.bypass"
  #Permission to bypass cooldown.
  Search-bypass-cooldown: "betterheads.search.cooldownbypass"

Options:
  Debug: false
  Fast-load:
    Warning:
    - "This is a BETA feature. There is NO WARRANTY that this actually helps heads loading process."
    - "This message is only visible in config file and will never be sent to any player."
    - "REMINDER: THERE IS NO WARRANTY THAT THIS MAKES LOADING FASTER, IT's JUST A TEST."
    - "If you have any issues with this enabled, disable and restart your server."
    - "This COULD CAUSE TPS drops, make sure you test it first before using it in your server."
    Enabled: false
  Permission-per-head:
    #If enabled, each heads will require an specific permission to be obtained/purchased
    #This is disabled by default. Enable it ONLY IF YOU PLAN TO GIVE PERMISSION MANUALLY.
    Enabled: false
    #This is the permission format for each head. This must contain {ID} word.
    #It will be replaced with the head ID. If head id is 14000, the permission
    #required for that head will be "betterheads.head.14000"
    Permission: "betterheads.head.{ID}"
  #To apply changes for aliases you must RESTART the server.
  #Plugman or similar plugins are NOT and will NEVER be supported.
  #Use /reload or restart your server.
  Aliases:
  - "bheads"
  - "bhead"
  - "bettehead"
  Check-new-heads:
    #If true, plugin will attempt to check for new heads on server start.
    #If enabled, it could take more time to start the server. This cannot be avoided.
    #If false, plugin will not check for new heads, it means new heads won't be added.
    #Recommended to leave it as true. THIS IS IGNORED ON FIRST LAUNCH.
    On-start: true
    #Time in minutes between new update checks. This will be run asynchronously. Default: 1440 (1 day)
    #Set to 0 to disable check task.
    Interval: 1440
  Search:
    #Minimum amount of letters for search function.
    Minimum-length: 3
    #Enable cooldown for players in creative mode?
    Cooldown-on-creative: true
    #Time in seconds for search cooldown.
    Time: 10
  Gui:
    Main-title: "&8Available heads"
    Category-title: "&8Category: {CATEGORY} ({PAGE}/{MAX})"
    #This option hides category if player doesn't have permission.
    Hide-locked: true
    #Fills empty slots with frames.
    Fill-with-frame: true
    Items:
      Previous:
        Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzdhZWU5YTc1YmYwZGY3ODk3MTgzMDE1Y2NhMGIyYTdkNzU1YzYzMzg4ZmYwMTc1MmQ1ZjQ0MTlmYzY0NSJ9fX0="
        Displayname: "&9Previous page"
        Lore:
        - "&7Return to previous page."
      Next:
        Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgyYWQxYjljYjRkZDIxMjU5YzBkNzVhYTMxNWZmMzg5YzNjZWY3NTJiZTM5NDkzMzgxNjRiYWM4NGE5NmUifX19"
        Displayname: "&9Next page"
        Lore:
        - "&7Move to next page."
      Unknown:
        Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiYTYzMzQ0ZjQ5ZGQxYzRmNTQ4OGU5MjZiZjNkOWUyYjI5OTE2YTZjNTBkNjEwYmI0MGE1MjczZGM4YzgyIn19fQ=="
        Displayname: "&4&lUnknown category"
        Lore:
        - "&7You haven't unlocked"
        - "&7this category."
      Close:
        Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ=="
        Displayname: "&4&lClose"
        Lore:
        - "&7Close Heads GUI."
      Back:
        Texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmViNTg4YjIxYTZmOThhZDFmZjRlMDg1YzU1MmRjYjA1MGVmYzljYWI0MjdmNDYwNDhmMThmYzgwMzQ3NWY3In19fQ=="
        Displayname: "&4&lBack"
        Lore:
        - "&7Back to GUI."
      Category:
        Displayname: "&b&l{CATEGORY}"
        Lore:
        - "&7{AMOUNT} heads!"
      Jump:
        #This can be "CUSTOM_HEAD" or any other material.
        Material: PAPER
        #Texture if material is "CUSTOM_HEAD"
        Texture: "ewogICJ0aW1lc3RhbXAiIDogMTU5NDQ0NjkyMDI5NiwKICAicHJvZmlsZUlkIiA6ICJlMWMxYTE5NDdlODY0MTRmODZiYjQyZDgyYTIxY2ZiOCIsCiAgInByb2ZpbGVOYW1lIiA6ICJBbG9uc29BbGlhZ2EiLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTY4YWE3NGNjODg1NzgwNjBkMGZlM2JkOTA4YjM0ZjY5ZjEyZTA3ZjFmODljNWRkYzE1ZTZiZjYwZjA0Y2NjNiIKICAgIH0KICB9Cn0="
        Displayname: "&aPage {PAGE}"
  Head:
    Displayname: "&e{NAME}"
    Displayname-id: "&e{NAME}&r &8{ID}"
    Lore-vault:
    - "&7Cost: &a${PRICE}"
    Lore-levels:
    - "&7Cost: &a{PRICE} level(s)"
    Lore-material:
    - "&7Cost: &a{PRICE} {MATERIAL}"
  Head-cost:
    #If disabled, cost will be disabled for everything.
    Enabled: true
    Cost-on-creative: false
    #Available types are VAULT,LEVEL and MATERIAL.
    #1) VAULT will attempt to hook with vault plugin.
    #If disabled, cost will take levels. YES, LEVELS, not experiences, LEVELS.
    #If enabled and Vault is available and hooked, cost will take money from balance, otherwise it will take LEVELS.
    #This is an experimental feature, please report bugs on discussion tab.
    #2) LEVEL will use player level(experience)
    #3) MATERIAL will require the specified material
    #   First it will check player's main hand, and then the inventory.
    Type: LEVEL
    #Material used if type is "MATERIAL"
    #This material will be required as payment to purchase heads.
    Material: "DIAMOND"
    Cost: 1
    #If enabled
  Head-command:
    #If enabled using the /betterheads head will have a cost. (ONLY IF PRICE FOR HEADS ARE ENABLED, COST WILL BE THE SAME)
    Cost: true
    #If enabled using the /betterheads head will have a cooldown. (ONLY IF COOLDOWN FOR HEADS IS ENABLED)
    Cooldown: true
  #Add a delay to prevent players get/buy heads to fast.
  #Cooldown does NOT persist on restart. So make sure you choose short cooldown interval.
  Cooldown:
    Cooldown-on-creative: false
    #Time is in SECONDS. (Default: 5 seconds)
    #Example: 60 = 1 minute, 300 = 5 minutes.
    #Set to 0 to disable cooldown.
    Time: 5

Items:
  Frame:
    Color: "BLACK"
    #Only 1.14+
    Custom-model-data: 0

Updates:
  #Auto update configuration? Enabling will delete comments.
  Auto-update-configuration: true
  #Check for updates? Recommended to keep it enabled.
  Check-updates: true
  #Notify updates when player with permission joins the server?
  Notify-updates: true
  #Permission required to receive update message.
  Permission: "betterheads.update"
  #Message to send when update is found.
  Message: "&4[BetterHeads] &eA new update has been found! You are using version {CURRENT}. Download version {NEW} here &c{LINK}"
